-- MySQL Script generated by MySQL Workbench
-- qua 23 mai 2018 22:34:21 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Person` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `namePerson` VARCHAR(255) NOT NULL,
  `tel1Person` VARCHAR(50) NOT NULL,
  `tel2Person` VARCHAR(50) NULL,
  PRIMARY KEY (`idPerson`),
  UNIQUE INDEX `idPerson_UNIQUE` (`idPerson` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LegalPerson`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LegalPerson` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LegalPerson` (
  `idLegal Person` INT NOT NULL AUTO_INCREMENT,
  `cpfLegalPerson` VARCHAR(45) NOT NULL,
  `rgLegalPerson` VARCHAR(45) NOT NULL,
  `Person_idPerson` INT NOT NULL,
  PRIMARY KEY (`idLegal Person`, `Person_idPerson`),
  UNIQUE INDEX `cpfLegalPerson_UNIQUE` (`cpfLegalPerson` ASC),
  INDEX `fk_LegalPerson_Person1_idx` (`Person_idPerson` ASC),
  CONSTRAINT `fk_LegalPerson_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JuridicalPerson`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`JuridicalPerson` ;

CREATE TABLE IF NOT EXISTS `mydb`.`JuridicalPerson` (
  `idJuridicalPerson` INT NOT NULL AUTO_INCREMENT,
  `cnpjJuridicalPerson` VARCHAR(45) NOT NULL,
  `Person_idPerson` INT NOT NULL,
  PRIMARY KEY (`idJuridicalPerson`, `Person_idPerson`),
  UNIQUE INDEX `idJuridical Person_UNIQUE` (`idJuridicalPerson` ASC),
  UNIQUE INDEX `cnpjJuridicalPerson_UNIQUE` (`cnpjJuridicalPerson` ASC),
  INDEX `fk_JuridicalPerson_Person_idx` (`Person_idPerson` ASC),
  CONSTRAINT `fk_JuridicalPerson_Person`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`State`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`State` ;

CREATE TABLE IF NOT EXISTS `mydb`.`State` (
  `idState` INT NOT NULL AUTO_INCREMENT,
  `nameState` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idState`),
  UNIQUE INDEX `idState_UNIQUE` (`idState` ASC),
  UNIQUE INDEX `nameState_UNIQUE` (`nameState` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`City` ;

CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `State_idState` INT NOT NULL,
  `nameCity` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`State_idState`),
  CONSTRAINT `fk_City_State1`
    FOREIGN KEY (`State_idState`)
    REFERENCES `mydb`.`State` (`idState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `Person_idPerson` INT NOT NULL,
  `City_State_idState` INT NOT NULL,
  `streetAddress` VARCHAR(255) NOT NULL,
  `numberAddress` INT NOT NULL,
  `districtAddress` VARCHAR(45) NULL,
  PRIMARY KEY (`Person_idPerson`, `City_State_idState`),
  INDEX `fk_Address_City1_idx` (`City_State_idState` ASC),
  CONSTRAINT `fk_Address_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Address_City1`
    FOREIGN KEY (`City_State_idState`)
    REFERENCES `mydb`.`City` (`State_idState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Supplier` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `idSupplier` INT NOT NULL AUTO_INCREMENT,
  `nameSupplier` VARCHAR(255) NOT NULL,
  `JuridicalPerson_idJuridicalPerson` INT NOT NULL,
  PRIMARY KEY (`idSupplier`, `JuridicalPerson_idJuridicalPerson`),
  INDEX `fk_Supplier_JuridicalPerson1_idx` (`JuridicalPerson_idJuridicalPerson` ASC),
  CONSTRAINT `fk_Supplier_JuridicalPerson1`
    FOREIGN KEY (`JuridicalPerson_idJuridicalPerson`)
    REFERENCES `mydb`.`JuridicalPerson` (`idJuridicalPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Brand` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `idBrand` INT NOT NULL AUTO_INCREMENT,
  `nameBrand` VARCHAR(45) NULL,
  PRIMARY KEY (`idBrand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier_has_Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Supplier_has_Brand` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Supplier_has_Brand` (
  `Supplier_idSupplier` INT NOT NULL,
  `Brand_idBrand` INT NOT NULL,
  PRIMARY KEY (`Supplier_idSupplier`, `Brand_idBrand`),
  INDEX `fk_Supplier_has_Brand_Brand1_idx` (`Brand_idBrand` ASC),
  CONSTRAINT `fk_Supplier_has_Brand_Supplier1`
    FOREIGN KEY (`Supplier_idSupplier`)
    REFERENCES `mydb`.`Supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supplier_has_Brand_Brand1`
    FOREIGN KEY (`Brand_idBrand`)
    REFERENCES `mydb`.`Brand` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `barCodeProduct` VARCHAR(255) NOT NULL,
  `nameProduct` VARCHAR(255) NOT NULL,
  `priceProduct` FLOAT NOT NULL,
  `quantityProduct` INT NOT NULL DEFAULT 0,
  `Brand_idBrand` INT NOT NULL,
  PRIMARY KEY (`barCodeProduct`, `Brand_idBrand`),
  INDEX `fk_Product_Brand1_idx` (`Brand_idBrand` ASC),
  CONSTRAINT `fk_Product_Brand1`
    FOREIGN KEY (`Brand_idBrand`)
    REFERENCES `mydb`.`Brand` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmployeeType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EmployeeType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EmployeeType` (
  `idEmployeeType` INT NOT NULL,
  `nameEmployeeType` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idEmployeeType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `LegalPerson_idLegal Person` INT NOT NULL,
  `loginEmployee` VARCHAR(30) NOT NULL,
  `passwordEmployee` VARCHAR(50) NOT NULL,
  `EmployeeType_idEmployeeType` INT NOT NULL,
  PRIMARY KEY (`LegalPerson_idLegal Person`, `EmployeeType_idEmployeeType`),
  INDEX `fk_Employee_EmployeeType1_idx` (`EmployeeType_idEmployeeType` ASC),
  CONSTRAINT `fk_Employee_LegalPerson1`
    FOREIGN KEY (`LegalPerson_idLegal Person`)
    REFERENCES `mydb`.`LegalPerson` (`idLegal Person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_EmployeeType1`
    FOREIGN KEY (`EmployeeType_idEmployeeType`)
    REFERENCES `mydb`.`EmployeeType` (`idEmployeeType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Registry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Registry` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Registry` (
  `idRegistry` INT NOT NULL,
  `Employee_LegalPerson_Person_idPerson` INT NOT NULL,
  `dateRegistry` DATE NOT NULL,
  `valueRegistry` FLOAT NOT NULL,
  `typeRegistry` INT NOT NULL,
  `Person_idPerson` INT NOT NULL,
  PRIMARY KEY (`idRegistry`, `Employee_LegalPerson_Person_idPerson`),
  INDEX `fk_Registry_Person1_idx` (`Person_idPerson` ASC),
  CONSTRAINT `fk_Registry_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `mydb`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Transaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Transaction` (
  `idTransaction` INT NOT NULL,
  `idRegistry_Transaction` INT NOT NULL,
  `valueTransaction` FLOAT NOT NULL,
  PRIMARY KEY (`idTransaction`, `idRegistry_Transaction`),
  INDEX `fk_Transaction_Registry_idx` (`idRegistry_Transaction` ASC),
  CONSTRAINT `fk_Transaction_Registry`
    FOREIGN KEY (`idRegistry_Transaction`)
    REFERENCES `mydb`.`Registry` (`idRegistry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ServiceType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ServiceType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ServiceType` (
  `idServiceType` INT NOT NULL AUTO_INCREMENT,
  `nameServiceType` VARCHAR(45) NULL,
  `priceServiceType` VARCHAR(45) NULL,
  PRIMARY KEY (`idServiceType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OperationType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OperationType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OperationType` (
  `idServiceStatus` INT NOT NULL AUTO_INCREMENT,
  `nameServiceStatus` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idServiceStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Service` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Service` (
  `idService` INT NOT NULL AUTO_INCREMENT,
  `startDateService` DATE NOT NULL,
  `estimatedEndDateService` DATE NOT NULL,
  `valueService` FLOAT NOT NULL,
  `Employee_EmployeeType_idEmployeeType` INT NOT NULL,
  `ServiceType_idServiceType` INT NOT NULL,
  `ServiceStatus_idServiceStatus` INT NOT NULL,
  PRIMARY KEY (`idService`, `Employee_EmployeeType_idEmployeeType`, `ServiceType_idServiceType`, `ServiceStatus_idServiceStatus`),
  INDEX `fk_Service_Employee1_idx` (`Employee_EmployeeType_idEmployeeType` ASC),
  INDEX `fk_Service_ServiceType1_idx` (`ServiceType_idServiceType` ASC),
  INDEX `fk_Service_ServiceStatus1_idx` (`ServiceStatus_idServiceStatus` ASC),
  CONSTRAINT `fk_Service_Employee1`
    FOREIGN KEY (`Employee_EmployeeType_idEmployeeType`)
    REFERENCES `mydb`.`Employee` (`EmployeeType_idEmployeeType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_ServiceType1`
    FOREIGN KEY (`ServiceType_idServiceType`)
    REFERENCES `mydb`.`ServiceType` (`idServiceType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_ServiceStatus1`
    FOREIGN KEY (`ServiceStatus_idServiceStatus`)
    REFERENCES `mydb`.`OperationType` (`idServiceStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
